### ISSUE TITLE
Error "unauthorized": "Authentication required"

### ISSUE THREAD

**Issue by iampavan** [CytadelHosting/patch_server_updater#1]
If the PatchServer has an API token created, then the patch_server_updater scripts errors out.

> JSON : /Users/admin/Desktop/CiscoAnyConnectSecureMobilityClient.json
> URL : https://abc.com/
> CONFIG : /Users/admin/Desktop/AnyConnect.conf
> Input JSON checked, seems to be OK, checking patch server access ...
> Ok, https://abc.com is recheable, trying to push JSON file to the API.
> Push failed, check api response here :
> {
>   "unauthorized": "Authentication required"
> }

I do have the API token, but how do I pass it in the script?

FYI :
If the PatchServer does not have API token generated, then the patch_server_updater scripts works fine.

> JSON : /Users/admin/Desktop/ParallelsDesktop.json
> URL : https://abc.com/
> CONFIG : /Users/admin/Desktop/ParallelsDesktop.conf
> Input JSON checked, seems to be OK, checking patch server access ...
> Ok, https://abc.com is recheable, trying to push JSON file to the API.
> Push success, /Users/admin/Desktop/ParallelsDesktop.conf will be generate soon
> /Users/admin/Desktop/ParallelsDesktop.conf config file generated !
> patch_server_updater.sh [add] will be able to update a new version of ParallelsDesktop if you can parse a website and collect informations

**Comment by fabiencytadel** [comment]
Hello,
thank for your message, we didn't use this option with our patch server. I will check the code to implement that soon.

**Comment by iampavan** [comment]
Thank you for your quick response. Appreciate it. ☺️

**Comment by fabiencytadel** [comment]
Hello !

could you test the new feature on this branch ?

https://github.com/CytadelHosting/patch_server_updater/tree/add_http_header_for_API_with_token

Thanks !

**Comment by iampavan** [comment]
Hey hey!
Tested. Works perfectly fine.

Thank you.

**Comment by iampavan** [comment]
Just couple of things I noticed. (I don't mean to nitpick, it's just that I love your tool and want to help it make better).

1. Line 218 in the code. Typo in **_reachable_
2. While I pass the json file when I run the patch_server_updater.sh script and if the path has any "spaces" along the way, then it fails.

Eg 1 :
```
./patch_server_updater.sh init -j "/Users/admin/Dropbox (ABC Group)/CiscoAnyConnectSecureMobilityClient.json" -u https://abc.com -o ~/Desktop/AnyConnect.conf -t xxxyyyzzz
```
Outputs:

> JSON : /Users/admin/Dropbox (ABC Group)/CiscoAnyConnectSecureMobilityClient.json
> URL : https://abc.com
> CONFIG : /Users/admin/Desktop/AnyConnect.conf
> TOKEN : xxxyyyzzz
> cat: /Users/admin/Dropbox: No such file or directory
> cat: (ABC: No such file or directory
> cat: Group)/CiscoAnyConnectSecureMobilityClient.json: No such file or directory
> Name ID field is missing in the config file

Eg 2:
```
./patch_server_updater.sh init -j /Users/admin/Dropbox\ \(ABC\ Group\)/CiscoAnyConnectSecureMobilityClient.json -u https://abc.com -o ~/Desktop/AnyConnect.conf -t xxxyyyzzz
```

Outputs:

> JSON : /Users/admin/Dropbox (ABC Group)/CiscoAnyConnectSecureMobilityClient.json
> URL : https://abc.com
> CONFIG : /Users/admin/Desktop/AnyConnect.conf
> TOKEN : xxxyyyzzz
> cat: /Users/admin/Dropbox: No such file or directory
> cat: (ABC: No such file or directory
> cat: Group)/CiscoAnyConnectSecureMobilityClient.json: No such file or directory
> Name ID field is missing in the config file

Workaround: I place the json file on my Desktop and run it, it works well.

```
./patch_server_updater.sh init -j "/Users/admin/Desktop/CiscoAnyConnectSecureMobilityClient.json" -u https://abc.com -o ~/Desktop/AnyConnect.conf -t xxxyyyzzz
```

Outputs:

> JSON : /Users/admin/Desktop/CiscoAnyConnectSecureMobilityClient.json
> URL : https://abc.com
> CONFIG : /Users/admin/Desktop/AnyConnect.conf
> TOKEN : xxxyyyzzz
> Input JSON checked, seems to be OK, checking patch server access ...
> Ok, https://abc.com is recheable, trying to push JSON file to the API.
> Push success, /Users/admin/Desktop/AnyConnect.conf will be generate soon
> /Users/admin/Desktop/AnyConnect.conf config file generated !
> patch_server_updater.sh [add] will be able to update a new version of CiscoAnyConnectSecureMobilityClient if you can parse a website and collect informations

**Comment by fabiencytadel** [comment]
Hello Pavan, don't worry, i'm happy you like the script.

I made some corrections, could you try ?
Thanks !

**Comment by iampavan** [comment]
Awesome. Works great!

Thank you Fabien.

**Comment by fabiencytadel** [comment]
Nice ! Thanks for your help !
